[tox]
env_list = py39
no_package = true

[testenv]
description = Run linting, formatting, and tests
deps =
    -rrequirements.txt
commands =
    black --check .
    black .
    ruff check .
    pytest