name: Pet Retail CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**

  pull_request:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION : "3.11"
  TERRAFORM_VERSION: "1.13.0"


jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff
        run: ruff check .

      - name: Run Black
        run: black --check .


  test:

    runs-on: ubuntu-latest

    steps:
      - name : checkout repository
        uses: actions/checkout@v4

      - name : Setup Python
        uses : actions/setup-python@v5
        with :
          python-version : ${{ env.PYTHON_VERSION }}

      - name : install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest


  terraform:

    runs-on : ubuntu-latest

    steps:
      - name : checkout repository
        uses : actions/checkout@v4

      - name : Install Terraform
        uses : hashicorp/setup-terraform@v3
        with :
          terraform-version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Format Check
        working-directory: terraform/environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -input=false


  deploy :
    needs : 
      - lint
      - test
      - terraform

    runs-on : ubuntu-latest

    # if: github.ref == 'refs/heads/main'
    if: startsWith(github.ref, 'refs/heads/feature/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp \
            src/glue_jobs/foundation/init_metadata.py \
            s3://${{ vars.S3_BUCKET }}/${{ vars.GLUE_SCRIPT_S3_KEY }}

      - name: Start Glue Job
        id: start_glue
        run: |
          JOB_RUN_ID=$(aws glue start-job-run \
            --job-name "${{ vars.GLUE_JOB_NAME }}" \
            --query 'JobRunId' \
            --output text)
          echo "Started Glue Job: $JOB_RUN_ID"
          echo "JOB_RUN_ID=$JOB_RUN_ID" >> "$GITHUB_OUTPUT"

      - name: Wait for Glue Job
        run: |
          JOB_RUN_ID="${{ steps.start_glue.outputs.JOB_RUN_ID }}"
          echo "Monitoring Glue Job..."
          echo "Run ID: $JOB_RUN_ID"

          while true
          do
            STATUS=$(aws glue get-job-run \
              --job-name "${{ vars.GLUE_JOB_NAME }}" \
              --run-id "$JOB_RUN_ID" \
              --query 'JobRun.JobRunState' \
              --output text)

            echo "Current Status : $STATUS"

            if [[ "$STATUS" == "SUCCEEDED" ]]; then
              echo "Glue Job Succeeded"
              break
            fi

            if [[ "$STATUS" == "FAILED" || \
                  "$STATUS" == "STOPPED" || \
                  "$STATUS" == "TIMEOUT" ]]; then

              echo "Glue Job Failed"
              exit 1
            fi

            sleep 20

          done

      - name: Deployment Summary
        if: success()

        run: |
          echo "# Glue Deployment Summary " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "| Item | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Glue Job | ${{ vars.GLUE_JOB_NAME }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Job Run ID | ${{ steps.start_glue.outputs.JOB_RUN_ID }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Status | SUCCESS |" >> $GITHUB_STEP_SUMMARY


  